steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build app1'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app1:latest'
  - './app1'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push Docker Image for app1'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app1:latest'


- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy app1'
  entrypoint: 'bash'
  args:
  - '-c'
  - kubectl apply -f app1/deployment.yaml


options:
  logging: CLOUD_LOGGING_ONLY

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'Build Docker Image for app2'
#   args: ['cd', 'app2', '&&', 'build', '-t', 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app2', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   id: 'push Docker Image for app2'
#   args: ['push', 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app2']

# create k8s cluster aur update image 
